config/routes.rb
Rails.application.routes.draw do
  root 'reviews#index'
  resources :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @review = Review.order("RANDOM()").first
  end

  def new
    @review = Review.new
  end

  def create
    Review.create(review_params)
    redirect_to root_path
  end

  private

  def review_params
    params.permit(:name, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quizzes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
    <br />
    <h1>Quiz One</h1>
    <br />
    <h2>This was a page with static content.</h2>
    <ol>
      <li>It is a rails application.</li>
      <li>It is hosted on <b>Heroku</b>.</li>
      <li>The code is hosted on <b>GitHub</b>.</li>
      <li><i>The headline is a non-black color.</i></li>
    </ol>
    <br />
    <br />
    <h1>Quiz Two</h1>
    <br />
    <ol>
      <li>This page now has a model and database.</li>
      <li>It has the <b>SimpleForm</b> gem and a <i>form.</i></li>
    </ol>
    <ul>
    <li><%= link_to 'Contribute', new_review_path %></li>
    </ul>

app/views/reviews/new.html.erb
<h1>Reviews</h1>
<%= simple_form_for @review do |f| %>
  <%= f.input :name %>
  <%= f.input :comment %>
  <br />
  <%= f.submit 'Submit', class: 'btn btn-danger' %>
<% end %>